# Generated by Django 4.0 on 2023-04-06 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_activation_otpcode'),
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grade',
            new_name='cotes',
        ),
    ]
