# Generated by Django 4.0 on 2023-04-06 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verify.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='promo',
            field=models.CharField(max_length=250),
        ),
    ]
